name: Docker Build Test

on:
  pull_request:
    paths:
      - "**.py"
      - "Dockerfile"
      - "uv.lock"
      - ".python-version"
      - "pyproject.toml"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: "Build Docker Image"
        run: |
          docker build .
